[files]
extend-exclude = [
    "*.pem",
    "Jenkinsfile",
    "libcaf_core/caf/detail/parser/read_bool.hpp",
    "libcaf_core/caf/detail/parser/read_bool.test.cpp",
    "libcaf_net/test/pem.cpp",
]

[default.extend-words]
PN = "PN"
Yout = "Yout"
aout = "aout"
caf = "caf"
ws = "ws"
parametrized = "parametrized"
unexpect = "unexpect"
