[files]
extend-exclude = ["*.pem", "libcaf_net/test/pem.cpp", "Jenkinsfile"]

[default.extend-words]
PN = "PN"
Yout = "Yout"
aout = "aout"
caf = "caf"
ws = "ws"
fals = "fals"
parametrized = "parametrized"
