name: build-caf
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  Windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: egor-tensin/vs-shell@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: python -m pip install -r robot/dependencies.txt
    - run: choco install openssl --no-progress
    - name: Build
      run: .ci/windows/build.cmd
    - name: Test
      run: .ci/windows/test.cmd
    - name: Archive Robot logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot-logs
        path: build/robot-output/
