# Note: we use a build with exceptions disabled for gcov, because it generates
#       more accurate stats on branches.
name: codecov
on:
  pull_request:
  push:
    branches:
      - master
env:
  CTEST_NO_TESTS_ACTION: error

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install-robot
      run:  pip install -r robot/dependencies.txt
    - name: configure
      run: |
        cmake \
          -S . \
          -B build \
          -DCAF_ENABLE_ROBOT_TESTS:BOOL=ON \
          -DCAF_LOG_LEVEL:STRING=TRACE \
          -DCMAKE_CXX_FLAGS:STRING="--coverage -O0" \
          -DCMAKE_BUILD_TYPE:STRING=Debug \
          -DBUILD_SHARED_LIBS:BOOL=OFF
    - name: build
      run: make -C build -j 4
    - name: test
      run: ctest --test-dir build
    - name: upload-coverage
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        gcov: true
        gcov_args: --exclude-throw-branches
        token: ${{ secrets.CODECOV_TOKEN  }}
