name: debug-builds

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/CMakeLists.txt'
      - 'cmake/**'
      - '.github/workflows/**'
  push:
    branches:
      - main

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_OUTPUT_ON_FAILURE: ON

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: egor-tensin/vs-shell@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: python -m pip install -r robot/dependencies.txt
      - run: choco install openssl.light --no-progress
      - name: Build
        run: .ci/windows/build.cmd
      - name: Test
        run: .ci/windows/test.cmd
      - name: Archive Robot logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-logs
          path: build/robot-output/

  asan-and-ubsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install-robot
        run:  pip install -r robot/dependencies.txt
      - name: configure
        run: ./configure --dev-mode --generator=Ninja
      - name: build
        run: cmake --build build
      - name: test
        run: ctest --test-dir build

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install-robot
        run:  pip install -r robot/dependencies.txt
      - name: configure
        run: ./configure --coverage --generator=Ninja
      - name: build
        run: cmake --build build
      - name: test
        run: ctest --test-dir build
      - name: upload-coverage
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          gcov: true
          gcov_args: --exclude-throw-branches
          token: ${{ secrets.CODECOV_TOKEN  }}
