name: quality-checks

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/CMakeLists.txt'
      - 'cmake/**'
      - '.github/workflows/**'
  push:
    branches:
      - main

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format-19
        run: |
          sudo apt-get update -y \
            && sudo apt-get install -y --no-install-recommends \
              clang-format-19
      - name: clang-format
        run: |
          find libcaf* -name '*.[ch]pp' | xargs clang-format-19 --dry-run --Werror

  spell-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: spell-checking
        uses: crate-ci/typos@master
        with:
          config: .typos-config.toml

  forbidden-includes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: forbidden-includes
        run: |
          find libcaf_* -name '*hpp' -type f | grep -v 'caf/internal/' | xargs python3 scripts/forbidden-includes-check.py

  type-id-block-offsets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: type-id-block-offsets
        run: python3 scripts/get-next-free-block-offset.py 1>/dev/null && echo OK
